# Generated by Django 4.0.1 on 2022-03-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('is_email', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tbl_borrower_master',
                'managed': True,
            },
        ),
    ]
