# Generated by Django 4.0.1 on 2022-03-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanofficer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='token_user_id', to='loanofficer.usermaster')),
            ],
            options={
                'db_table': 'tbl_token_list',
                'managed': True,
            },
        ),
    ]
