# Generated by Django 4.0.1 on 2022-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenmaster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tokenmaster',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='tokenmaster',
            name='token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
