# Generated by Django 4.0.1 on 2022-03-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_tokenmaster_id_remove_tokenmaster_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenmaster',
            name='updated_date',
        ),
    ]
