# Generated by Django 4.0.1 on 2022-03-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=10240)),
                ('sender_id', models.IntegerField()),
                ('published', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nps_type', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'tbl_nps_reviews',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TellUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_score', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'tbl_nps_tell_us',
                'managed': True,
            },
        ),
    ]
